name: Schema Checks

on:
  pull_request:
    branches: [main]

jobs:
  check-files:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Bun
        run: curl -fsSL https://bun.sh/install | bash
      
      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH
      
      - name: Run checks
        run: bun run .github/scripts/check.js